[2021-10-08 00:38:42,455] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-07T00:00:00+00:00 [queued]>
[2021-10-08 00:38:42,622] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-07T00:00:00+00:00 [queued]>
[2021-10-08 00:38:42,627] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-08 00:38:42,629] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-08 00:38:42,630] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-08 00:38:42,715] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-07T00:00:00+00:00
[2021-10-08 00:38:42,758] {standard_task_runner.py:52} INFO - Started process 5239 to run task
[2021-10-08 00:38:42,795] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-07T00:00:00+00:00', '--job-id', '158', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp6hyuvroj', '--error-file', '/tmp/tmpdferrrl7']
[2021-10-08 00:38:42,808] {standard_task_runner.py:77} INFO - Job 158: Subtask Training_Model_A
[2021-10-08 00:38:43,170] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-07T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-08 00:38:43,519] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-07T00:00:00+00:00
[2021-10-08 00:38:43,635] {python.py:151} INFO - Done. Returned value was: None
[2021-10-08 00:38:43,695] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211007T000000, start_date=20211008T003842, end_date=20211008T003843
[2021-10-08 00:38:43,813] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-08 00:38:44,021] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
