[2021-10-05 00:13:14,125] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-04T00:00:00+00:00 [queued]>
[2021-10-05 00:13:14,244] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-04T00:00:00+00:00 [queued]>
[2021-10-05 00:13:14,252] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-05 00:13:14,254] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-05 00:13:14,257] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-05 00:13:14,310] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_C> on 2021-10-04T00:00:00+00:00
[2021-10-05 00:13:14,391] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_C', '2021-10-04T00:00:00+00:00', '--job-id', '118', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpstygpghz', '--error-file', '/tmp/tmp4k6_fc8m']
[2021-10-05 00:13:14,403] {standard_task_runner.py:77} INFO - Job 118: Subtask Training_Model_C
[2021-10-05 00:13:14,353] {standard_task_runner.py:52} INFO - Started process 66457 to run task
[2021-10-05 00:13:14,949] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_C 2021-10-04T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-05 00:13:15,304] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-10-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-04T00:00:00+00:00
[2021-10-05 00:13:15,402] {python.py:151} INFO - Done. Returned value was: None
[2021-10-05 00:13:15,488] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_C, execution_date=20211004T000000, start_date=20211005T001314, end_date=20211005T001315
[2021-10-05 00:13:15,619] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-05 00:13:15,896] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
