[2021-10-21 00:00:02,859] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-20T00:00:00+00:00 [queued]>
[2021-10-21 00:00:02,895] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-20T00:00:00+00:00 [queued]>
[2021-10-21 00:00:02,897] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 00:00:02,899] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-21 00:00:02,901] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-21 00:00:02,947] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-20T00:00:00+00:00
[2021-10-21 00:00:02,963] {standard_task_runner.py:52} INFO - Started process 29098 to run task
[2021-10-21 00:00:02,982] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-20T00:00:00+00:00', '--job-id', '224', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmph_an16uo', '--error-file', '/tmp/tmpmvgzifbw']
[2021-10-21 00:00:02,983] {standard_task_runner.py:77} INFO - Job 224: Subtask Training_Model_A
[2021-10-21 00:00:03,071] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-20T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-21 00:00:03,205] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-20T00:00:00+00:00
[2021-10-21 00:00:03,261] {python.py:151} INFO - Done. Returned value was: None
[2021-10-21 00:00:03,281] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211020T000000, start_date=20211021T000002, end_date=20211021T000003
[2021-10-21 00:00:03,373] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-21 00:00:03,442] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
