[2021-10-17 02:46:34,413] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-16T00:00:00+00:00 [queued]>
[2021-10-17 02:46:34,565] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-16T00:00:00+00:00 [queued]>
[2021-10-17 02:46:34,570] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-17 02:46:34,578] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-17 02:46:34,590] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-17 02:46:34,676] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-16T00:00:00+00:00
[2021-10-17 02:46:34,722] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-16T00:00:00+00:00', '--job-id', '206', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppqqetekg', '--error-file', '/tmp/tmpec2vp9t_']
[2021-10-17 02:46:34,728] {standard_task_runner.py:77} INFO - Job 206: Subtask Training_Model_A
[2021-10-17 02:46:34,706] {standard_task_runner.py:52} INFO - Started process 57103 to run task
[2021-10-17 02:46:35,027] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-16T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-17 02:46:35,307] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-16T00:00:00+00:00
[2021-10-17 02:46:35,433] {python.py:151} INFO - Done. Returned value was: None
[2021-10-17 02:46:35,505] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211016T000000, start_date=20211017T024634, end_date=20211017T024635
[2021-10-17 02:46:35,732] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-17 02:46:35,836] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
