[2021-10-12 00:00:08,000] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_B 2021-10-11T00:00:00+00:00 [queued]>
[2021-10-12 00:00:08,036] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_B 2021-10-11T00:00:00+00:00 [queued]>
[2021-10-12 00:00:08,039] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-12 00:00:08,040] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-12 00:00:08,041] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-12 00:00:08,062] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_B> on 2021-10-11T00:00:00+00:00
[2021-10-12 00:00:08,066] {standard_task_runner.py:52} INFO - Started process 90716 to run task
[2021-10-12 00:00:08,079] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_B', '2021-10-11T00:00:00+00:00', '--job-id', '178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphvpc7rjx', '--error-file', '/tmp/tmpwzd_j524']
[2021-10-12 00:00:08,081] {standard_task_runner.py:77} INFO - Job 178: Subtask Training_Model_B
[2021-10-12 00:00:08,201] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_B 2021-10-11T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-12 00:00:08,384] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-10-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-11T00:00:00+00:00
[2021-10-12 00:00:08,444] {python.py:151} INFO - Done. Returned value was: None
[2021-10-12 00:00:08,486] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_B, execution_date=20211011T000000, start_date=20211012T000008, end_date=20211012T000008
[2021-10-12 00:00:08,582] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-12 00:00:08,680] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
