[2021-10-02 19:11:14,818] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-02T19:11:13.174985+00:00 [queued]>
[2021-10-02 19:11:14,848] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-02T19:11:13.174985+00:00 [queued]>
[2021-10-02 19:11:14,854] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-02 19:11:14,856] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-02 19:11:14,858] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-02 19:11:14,891] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-02T19:11:13.174985+00:00
[2021-10-02 19:11:14,896] {standard_task_runner.py:52} INFO - Started process 19655 to run task
[2021-10-02 19:11:14,917] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-02T19:11:13.174985+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpdhr7js8_', '--error-file', '/tmp/tmpnmnbmrwv']
[2021-10-02 19:11:14,926] {standard_task_runner.py:77} INFO - Job 29: Subtask Training_Model_A
[2021-10-02 19:11:15,008] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-02T19:11:13.174985+00:00 [running]> on host d6b4131456ad
[2021-10-02 19:11:15,183] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-02T19:11:13.174985+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-02T19:11:13.174985+00:00
[2021-10-02 19:11:15,186] {python.py:151} INFO - Done. Returned value was: 3
[2021-10-02 19:11:15,269] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211002T191113, start_date=20211002T191114, end_date=20211002T191115
[2021-10-02 19:11:15,333] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-02 19:11:15,396] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
