[2021-10-05 14:04:28,314] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Accurate 2021-10-05T14:04:23.446447+00:00 [queued]>
[2021-10-05 14:04:28,344] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Accurate 2021-10-05T14:04:23.446447+00:00 [queued]>
[2021-10-05 14:04:28,346] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-05 14:04:28,348] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-05 14:04:28,350] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-05 14:04:28,370] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): Accurate> on 2021-10-05T14:04:23.446447+00:00
[2021-10-05 14:04:28,382] {standard_task_runner.py:52} INFO - Started process 82081 to run task
[2021-10-05 14:04:28,387] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Accurate', '2021-10-05T14:04:23.446447+00:00', '--job-id', '137', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp90sm29sd', '--error-file', '/tmp/tmpi_nxayq4']
[2021-10-05 14:04:28,390] {standard_task_runner.py:77} INFO - Job 137: Subtask Accurate
[2021-10-05 14:04:28,461] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Accurate 2021-10-05T14:04:23.446447+00:00 [running]> on host d6b4131456ad
[2021-10-05 14:04:28,556] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-05T14:04:23.446447+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-05T14:04:23.446447+00:00
[2021-10-05 14:04:28,559] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-05 14:04:28,563] {subprocess.py:63} INFO - Running command: ['bash', '-c', "printf '============\n\nAccurate\n\n=============' "]
[2021-10-05 14:04:28,578] {subprocess.py:74} INFO - Output:
[2021-10-05 14:04:28,585] {subprocess.py:78} INFO - ============
[2021-10-05 14:04:28,587] {subprocess.py:78} INFO - 
[2021-10-05 14:04:28,588] {subprocess.py:78} INFO - Accurate
[2021-10-05 14:04:28,589] {subprocess.py:78} INFO - 
[2021-10-05 14:04:28,590] {subprocess.py:78} INFO - =============
[2021-10-05 14:04:28,591] {subprocess.py:82} INFO - Command exited with return code 0
[2021-10-05 14:04:28,637] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Accurate, execution_date=20211005T140423, start_date=20211005T140428, end_date=20211005T140428
[2021-10-05 14:04:28,691] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-05 14:04:28,731] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
