[2021-10-10 01:59:30,591] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_B 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 01:59:30,711] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_B 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 01:59:30,713] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 01:59:30,714] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-10 01:59:30,716] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 01:59:30,772] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_B> on 2021-10-09T00:00:00+00:00
[2021-10-10 01:59:30,812] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_B', '2021-10-09T00:00:00+00:00', '--job-id', '169', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpl8p0gtsr', '--error-file', '/tmp/tmpkl5dlpqm']
[2021-10-10 01:59:30,820] {standard_task_runner.py:77} INFO - Job 169: Subtask Training_Model_B
[2021-10-10 01:59:30,800] {standard_task_runner.py:52} INFO - Started process 63757 to run task
[2021-10-10 01:59:31,034] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_B 2021-10-09T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-10 01:59:31,231] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 01:59:31,300] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 01:59:31,347] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_B, execution_date=20211009T000000, start_date=20211010T015930, end_date=20211010T015931
[2021-10-10 01:59:31,423] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 01:59:31,562] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
