[2021-10-07 00:00:02,656] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-06T00:00:00+00:00 [queued]>
[2021-10-07 00:00:02,696] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-06T00:00:00+00:00 [queued]>
[2021-10-07 00:00:02,697] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-07 00:00:02,698] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-07 00:00:02,700] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-07 00:00:02,722] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-06T00:00:00+00:00
[2021-10-07 00:00:02,731] {standard_task_runner.py:52} INFO - Started process 68019 to run task
[2021-10-07 00:00:02,749] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-06T00:00:00+00:00', '--job-id', '154', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpn0jpig65', '--error-file', '/tmp/tmpq6m158ql']
[2021-10-07 00:00:02,751] {standard_task_runner.py:77} INFO - Job 154: Subtask Training_Model_A
[2021-10-07 00:00:02,847] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-06T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-07 00:00:02,994] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-06T00:00:00+00:00
[2021-10-07 00:00:03,042] {python.py:151} INFO - Done. Returned value was: None
[2021-10-07 00:00:03,088] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211006T000000, start_date=20211007T000002, end_date=20211007T000003
[2021-10-07 00:00:03,182] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-07 00:00:03,290] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
