[2021-10-13 00:43:30,613] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 00:43:30,725] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 00:43:30,728] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 00:43:30,731] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-13 00:43:30,733] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 00:43:30,781] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-12T00:00:00+00:00
[2021-10-13 00:43:30,798] {standard_task_runner.py:52} INFO - Started process 48094 to run task
[2021-10-13 00:43:30,883] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-12T00:00:00+00:00', '--job-id', '185', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpjmgle1_r', '--error-file', '/tmp/tmpisuqsjy7']
[2021-10-13 00:43:30,893] {standard_task_runner.py:77} INFO - Job 185: Subtask Training_Model_A
[2021-10-13 00:43:31,155] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-12T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-13 00:43:31,402] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-12T00:00:00+00:00
[2021-10-13 00:43:31,463] {python.py:151} INFO - Done. Returned value was: None
[2021-10-13 00:43:31,534] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211012T000000, start_date=20211013T004330, end_date=20211013T004331
[2021-10-13 00:43:31,683] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-13 00:43:31,898] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
