[2021-10-13 00:43:30,666] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_B 2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 00:43:30,803] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_B 2021-10-12T00:00:00+00:00 [queued]>
[2021-10-13 00:43:30,804] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 00:43:30,815] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-13 00:43:30,822] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 00:43:30,882] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_B> on 2021-10-12T00:00:00+00:00
[2021-10-13 00:43:30,913] {standard_task_runner.py:52} INFO - Started process 48095 to run task
[2021-10-13 00:43:30,965] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_B', '2021-10-12T00:00:00+00:00', '--job-id', '183', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp5frnao61', '--error-file', '/tmp/tmp9zfojijl']
[2021-10-13 00:43:30,973] {standard_task_runner.py:77} INFO - Job 183: Subtask Training_Model_B
[2021-10-13 00:43:31,145] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_B 2021-10-12T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-13 00:43:31,372] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_B
AIRFLOW_CTX_EXECUTION_DATE=2021-10-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-12T00:00:00+00:00
[2021-10-13 00:43:31,453] {python.py:151} INFO - Done. Returned value was: None
[2021-10-13 00:43:31,490] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_B, execution_date=20211012T000000, start_date=20211013T004330, end_date=20211013T004331
[2021-10-13 00:43:31,600] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-13 00:43:31,769] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
