[2021-10-02 04:10:36,545] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-01T00:00:00+00:00 [queued]>
[2021-10-02 04:10:36,624] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_A 2021-10-01T00:00:00+00:00 [queued]>
[2021-10-02 04:10:36,627] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-02 04:10:36,630] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-02 04:10:36,632] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-02 04:10:36,751] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_A> on 2021-10-01T00:00:00+00:00
[2021-10-02 04:10:36,884] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_A', '2021-10-01T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpkg4q937a', '--error-file', '/tmp/tmpam1jy2i_']
[2021-10-02 04:10:36,919] {standard_task_runner.py:77} INFO - Job 5: Subtask Training_Model_A
[2021-10-02 04:10:36,847] {standard_task_runner.py:52} INFO - Started process 17331 to run task
[2021-10-02 04:10:37,088] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_A 2021-10-01T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-02 04:10:37,294] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-01T00:00:00+00:00
[2021-10-02 04:10:37,296] {python.py:151} INFO - Done. Returned value was: 2
[2021-10-02 04:10:37,571] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_A, execution_date=20211001T000000, start_date=20211002T041036, end_date=20211002T041037
[2021-10-02 04:10:37,731] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-02 04:10:37,937] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
