[2021-10-14 03:00:24,516] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 03:00:24,605] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 03:00:24,609] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 03:00:24,614] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-14 03:00:24,616] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 03:00:24,646] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_C> on 2021-10-13T00:00:00+00:00
[2021-10-14 03:00:24,661] {standard_task_runner.py:52} INFO - Started process 84030 to run task
[2021-10-14 03:00:24,703] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_C', '2021-10-13T00:00:00+00:00', '--job-id', '188', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp407belkq', '--error-file', '/tmp/tmpv_6ak4g9']
[2021-10-14 03:00:24,706] {standard_task_runner.py:77} INFO - Job 188: Subtask Training_Model_C
[2021-10-14 03:00:24,937] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_C 2021-10-13T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-14 03:00:25,156] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-13T00:00:00+00:00
[2021-10-14 03:00:25,223] {python.py:151} INFO - Done. Returned value was: None
[2021-10-14 03:00:25,255] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_C, execution_date=20211013T000000, start_date=20211014T030024, end_date=20211014T030025
[2021-10-14 03:00:25,347] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-14 03:00:25,442] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
