[2021-10-06 00:00:01,187] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-05T00:00:00+00:00 [queued]>
[2021-10-06 00:00:01,229] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-05T00:00:00+00:00 [queued]>
[2021-10-06 00:00:01,231] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-06 00:00:01,234] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-06 00:00:01,236] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-06 00:00:01,250] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_C> on 2021-10-05T00:00:00+00:00
[2021-10-06 00:00:01,258] {standard_task_runner.py:52} INFO - Started process 15102 to run task
[2021-10-06 00:00:01,273] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_C', '2021-10-05T00:00:00+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpqqlb11vx', '--error-file', '/tmp/tmpo0293oo6']
[2021-10-06 00:00:01,278] {standard_task_runner.py:77} INFO - Job 149: Subtask Training_Model_C
[2021-10-06 00:00:01,461] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_C 2021-10-05T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-06 00:00:01,629] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-10-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-05T00:00:00+00:00
[2021-10-06 00:00:01,766] {python.py:151} INFO - Done. Returned value was: None
[2021-10-06 00:00:01,808] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_C, execution_date=20211005T000000, start_date=20211006T000001, end_date=20211006T000001
[2021-10-06 00:00:01,857] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-06 00:00:01,934] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
