[2021-10-11 00:45:33,319] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-10T00:00:00+00:00 [queued]>
[2021-10-11 00:45:33,406] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.Training_Model_C 2021-10-10T00:00:00+00:00 [queued]>
[2021-10-11 00:45:33,407] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-11 00:45:33,409] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-10-11 00:45:33,412] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-11 00:45:33,453] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): Training_Model_C> on 2021-10-10T00:00:00+00:00
[2021-10-11 00:45:33,493] {standard_task_runner.py:52} INFO - Started process 69843 to run task
[2021-10-11 00:45:33,532] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'Training_Model_C', '2021-10-10T00:00:00+00:00', '--job-id', '174', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpffaho_qm', '--error-file', '/tmp/tmpibhuo_lk']
[2021-10-11 00:45:33,546] {standard_task_runner.py:77} INFO - Job 174: Subtask Training_Model_C
[2021-10-11 00:45:33,757] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.Training_Model_C 2021-10-10T00:00:00+00:00 [running]> on host d6b4131456ad
[2021-10-11 00:45:34,042] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=Training_Model_C
AIRFLOW_CTX_EXECUTION_DATE=2021-10-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-10T00:00:00+00:00
[2021-10-11 00:45:34,153] {python.py:151} INFO - Done. Returned value was: None
[2021-10-11 00:45:34,191] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=Training_Model_C, execution_date=20211010T000000, start_date=20211011T004533, end_date=20211011T004534
[2021-10-11 00:45:34,310] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-11 00:45:34,444] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
